### ISSUE TITLE
請問沒中獎的人，若有填寫資料我要去哪邊看？

### ISSUE THREAD

**Issue by jk2uTeresa** [sexyoung/song-beer-web#101]
請問沒中獎的人，若有填寫資料我要去哪邊看？
因為週週抽獎是
從沒中獎的人裡每週三挑出2個來贈獎
因此我會需要那些有填寫資料的人
才可以後續聯繫

**Comment by sexyoung** [comment]
我們有規定 `未中獎者的姓名與手機必填` 對吧? 所以照理說後台不會出現 沒填資料的未中獎者

**Comment by sexyoung** [comment]
雖說如此，但我還是在抽獎那邊加上判斷，只撈有填「姓名、手機與email」的未中獎者。並且，他沒中過獎，一旦他中過獎，他就不在名單內
