### ISSUE TITLE
若是一開始就掃到已掃過的QRcode 「繼續掃描QRcode」無法使用

### ISSUE THREAD

**Issue by jk2uTeresa** [sexyoung/song-beer-web#40]
繼續掃描QRcode 沒有反應

![000AHP7](https://user-images.githubusercontent.com/85104335/120589796-012a6600-c46c-11eb-9d78-fe5ff9657cd4.png)

<img width="369" alt="螢幕快照 2021-06-03 下午1 02 59" src="https://user-images.githubusercontent.com/85104335/120589823-0f788200-c46c-11eb-92cd-0a94cd82607f.png">

**Comment by sexyoung** [comment]
妳說的無法使用是什麼意思？我從lr 上看妳掃 `掃過的qrcode` 是沒問題的

**Comment by sexyoung** [comment]
OK 我發現了，正確的情況是：從 `原生相機` 去掃 `已掃過的qr` 會無法繼續

**Comment by sexyoung** [comment]
已修正，預計中午再上架

**Comment by jk2uTeresa** [comment]
好的，感謝：）
