### ISSUE TITLE
得獎結果頁顯示錯誤

### ISSUE THREAD

**Issue by jk2uTeresa** [sexyoung/song-beer-web#41]
應該要中野餐墊的結果頁面 出現行李箱

<img width="738" alt="螢幕快照 2021-06-03 下午2 30 28" src="https://user-images.githubusercontent.com/85104335/120598095-6edc8f00-c478-11eb-86ce-15f59eb30aba.png">

![IMG_5360](https://user-images.githubusercontent.com/85104335/120598203-916ea800-c478-11eb-839f-b553863b4615.PNG)

![IMG_5361](https://user-images.githubusercontent.com/85104335/120598568-fc1fe380-c478-11eb-939f-0bdb45e9fbad.PNG)

**Comment by AnnyJK2U** [comment]
咪兔 我應該是中水杯
但中獎的時候是行李箱
![IMG_5339](https://user-images.githubusercontent.com/83564239/120599153-b6174f80-c479-11eb-9545-e64b84ed8706.PNG)
![IMG_5342](https://user-images.githubusercontent.com/83564239/120599172-badc0380-c479-11eb-84e4-da8c33e5a3c1.PNG)
