### ISSUE TITLE
無法進行掃描

### ISSUE THREAD

**Issue by letitiajk2u** [sexyoung/song-beer-web#52]
掃描區域無法使用（ 測試裝置：iphone6s ）

![IMG_0052](https://user-images.githubusercontent.com/83579260/120814913-ecd88d00-c581-11eb-8ea0-19535513b04f.PNG)

**Comment by sexyoung** [comment]
https://caniuse.com/?search=webrtc
網頁掃描技術是從 iOS11 才開始支援，也就是 iPhoneX
