### ISSUE TITLE
同一個帳號中獎後已填寫資料了，第二次沒中獎，卻還是要填寫資料

### ISSUE THREAD

**Issue by jk2uTeresa** [sexyoung/song-beer-web#60]
同一個帳號應該只要填寫一次資料

剛剛中獎後已填寫資料了，第二次沒中獎，卻還是要填寫資料

![IMG_5390](https://user-images.githubusercontent.com/85104335/120950611-b6656280-c779-11eb-844d-570baa9c5b57.PNG)

![IMG_5391](https://user-images.githubusercontent.com/85104335/120950616-b82f2600-c779-11eb-81c6-bcb7c6baa832.PNG)

**Comment by sexyoung** [comment]
好，我會再改成 不用再打
