### ISSUE TITLE
後台得獎，

### ISSUE THREAD

**Issue by jk2uTeresa** [sexyoung/song-beer-web#62]

**Comment by jk2uTeresa** [comment]
開過獎的是不是要鎖起來～
今天的沒鎖

<img width="925" alt="螢幕快照 2021-06-07 上午10 35 56" src="https://user-images.githubusercontent.com/85104335/120952310-596bab80-c77d-11eb-9a5d-795eff6f3cea.png">

**Comment by sexyoung** [comment]
其實我好像本來有鎖，我忘了為何打開了，先請大家注意一下唄

**Comment by sexyoung** [comment]
改好了
