### ISSUE TITLE
表單無法送出（in-app）

### ISSUE THREAD

**Issue by letitiajk2u** [sexyoung/song-beer-web#66]
資料填寫完成後，按送出沒有反應

![2](https://user-images.githubusercontent.com/83579260/120967817-92664900-c79a-11eb-9c71-4fd4d4bcce8a.jpg)

**Comment by sexyoung** [comment]
因為 Safari 版本太舊不支援，我會換個寫法
https://caniuse.com/?search=FormData.get
![image](https://user-images.githubusercontent.com/1787867/120968457-7adb9000-c79b-11eb-9ceb-f94e0c7b3f82.png)
