### ISSUE TITLE
選單修改

### ISSUE THREAD

**Issue by hihikate** [sexyoung/song-beer-web#70]
登入前 <立即抽獎>
登入後<觀看得獎紀錄or立即抽獎>
這裡有點怪，所以是否可以給兩顆按鈕
譬如就是有<立即抽獎> <觀看得獎紀錄>。 這兩顆不一樣的按鈕
![S__14319758](https://user-images.githubusercontent.com/85104183/120985414-2ab9f900-c7ae-11eb-9991-e2d5f8d0fa61.jpg)

**Comment by sexyoung** [comment]
我有改了，妳們看一下是不是這樣

## 登入前
![image](https://user-images.githubusercontent.com/1787867/121023808-39b4a180-c7d6-11eb-8303-39d749f4cb93.png)


## 登入後
![image](https://user-images.githubusercontent.com/1787867/121023766-2b668580-c7d6-11eb-9466-ea69b6270641.png)

**Comment by sexyoung** [comment]
@hihikate 你看一下
