### ISSUE TITLE
流程頁面加入一個小小的字，有超連結醬子

### ISSUE THREAD

**Issue by hihikate** [sexyoung/song-beer-web#71]
![S__14319757](https://user-images.githubusercontent.com/85104183/120985845-94d29e00-c7ae-11eb-870e-867072ce2aac.jpg)

**Comment by jk2uTeresa** [comment]
我想跟客戶討論，或許可以用這樣的方式
等我明天早上確認唷（他下班了）

<img width="631" alt="螢幕快照 2021-06-07 下午6 55 36" src="https://user-images.githubusercontent.com/85104335/121005604-91e1a880-c7c2-11eb-8c55-35710fd1f28f.png">
