### ISSUE TITLE
中獎/沒中獎資料，若都沒填寫是否就無法送出也沒有任何提示

### ISSUE THREAD

**Issue by jk2uTeresa** [sexyoung/song-beer-web#77]
地址沒填寫完整或是地址/信箱擇一沒填，點確認送出沒任何反應也無法往下進行，消費者可能不知道問題出在哪，是否可跳一訊息請填寫完整收件地址或電子信箱

![S__45776966](https://user-images.githubusercontent.com/85104335/121149282-1bea4980-c875-11eb-8bd0-11d3fb300e42.jpg)

**Comment by sexyoung** [comment]
# 其實有出現提示耶
![image](https://user-images.githubusercontent.com/1787867/121200125-13f6cd80-c8a6-11eb-8e65-606967127a1b.png)
